# Generated by Django 4.1.7 on 2023-04-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crimenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('UbiId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crimenes.crimenes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
