# Generated by Django 4.1.7 on 2023-04-19 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
