# Generated by Django 4.1.7 on 2023-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimenes',
            fields=[
                ('CrimenId', models.AutoField(primary_key=True, serialize=False)),
                ('crime', models.CharField(max_length=255)),
            ],
        ),
    ]
