# Generated by Django 4.1.7 on 2023-04-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crimenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimenes',
            options={'permissions': [('can_create', 'Can create')]},
        ),
    ]
