# Generated by Django 4.1.7 on 2023-04-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crimenes', '0002_alter_crimenes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimenes',
            options={},
        ),
    ]
